# ------------------------------go
# Base image
# ------------------------------
FROM golang:1.24-alpine AS base

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# ------------------------------
# Testing image
# ------------------------------
FROM base AS testing

WORKDIR /app/cmd/web

RUN go build -o /app/bin/golang-react-todo-app

WORKDIR /app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
RUN chmod +x /app/bin/golang-react-todo-app
USER appuser

EXPOSE 8000

CMD ["bin/golang-react-todo-app"]